### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by gmorenz** [yusitnikov/puzzletv#1]
Is there any chance you would be willing to put this code under an open source license? I have a sudoku which apparently needs a slightly custom backend, and this seems like it might be a reasonable starting point (admittedly I haven't looked very closely yet since I'm currently unable to use it).

It's obviously up to you/the copyright holders, but it might be reasonable to exclude the puzzles from that license if you don't want people using them.

**Comment by yusitnikov** [comment]
I think that it would be reasonable to put the codebase under MIT and the puzzles under Creative Commons BY SA. WDYT? The license draft is here: https://github.com/yusitnikov/puzzletv/blob/add-license/LICENSE.md

Also, theoretically, I can put the framework into a separate repository and publish it to NPM, and leave this repo only for the puzzles themselves. This way, you can use the platform as a library and put your puzzle under whatever license you choose. But it would be a time-consuming task, so I'll do it only if absolutely necessary.

P.S. Feel free to contact me in Discord or Whatsapp if you want to speed up the discussion (see https://yusitnikov.github.io/puzzletv/#contacts)

**Comment by gmorenz** [comment]
I realized in the end that I could actually use sudokulab since it has the ability to draw lines from/to arbitrary points (and with a bit of work I managed to use the console to add a few hundred), so I have no immediate need for this. If I keep setting sudokus though, I know myself well enough to know that I'll want something custom sooner or later.

Those licenses seem like great choices to me, and thank you for your generosity :) The puzzle's part definitely seems like it needs permission of the authors if you don't have it already - I have no clue whether or not there is a commercial licensing market for puzzles that the authors might be worried about.

I don't think you need to change the code organization. It seems like a pretty safe assumption that anyone using this is going to want access to the internals to change things anyways, so publishing it to NPM seems unlikely to be that useful.
