### ISSUE TITLE
Rational Cube Highlighting error

### ISSUE THREAD

**Issue by ndinsmore** [yusitnikov/puzzletv#3]
I believe there is an error with the coloring of the 3 red as the is no cell with the 3 assigned.

<img width="1509" alt="image" src="https://github.com/yusitnikov/puzzletv/assets/45537276/d93b9062-3e45-4699-a021-00b3f9cfaca2">

**Comment by yusitnikov** [comment]
Hello!
Thanks for the concern!
There's a negative constraint on ratios in this puzzle, so all is good here. In these particular cells, 3 would be a 2:3 ratio with 2, and a 1:3 ratio with 1, so they indeed can't go there.
